default: &default
  adapter: mysql
  host: localhost
  username: root
  password: root
  database: a_converter
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: a_converter_test

production:
  <<: *default
